apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  database: c3BhcmtsbXNkYg==  # Base64 encoded value of the database username
  password: MTIzNDU2  # Base64 encoded value of the password
