apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 250Mi  # Adjust the storage size as per your requirements
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # Modify according to your storage class
  hostPath:
    path: /opt/mysql-data  # Update to the desired host path where you want to store MySQL data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi  # Adjust the storage size to match the PV size
  storageClassName: standard  # Modify according to your storage class
